# Generated by Django 2.0.4 on 2018-04-21 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_list', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('correct_answer', models.IntegerField()),
                ('answers', models.ManyToManyField(to='quiz.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('mother_tongue', models.CharField(max_length=30)),
                ('leader_board_score', models.IntegerField()),
                ('target_tongues', models.ManyToManyField(to='quiz.Language')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='rounds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Round'),
        ),
        migrations.AddField(
            model_name='game',
            name='user_list',
            field=models.ManyToManyField(to='quiz.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.ManyToManyField(to='quiz.User'),
        ),
    ]
